Repository jenkins-x-apps/jx-app-sso, pull requests merged in 2019-09, with the labels that each got.

#7 chore: bump sso operator
  jx-app-sso/requirements.yaml
Labels: approved, size/XS

#6 feat: support google auth
  README.md
  jx-app-sso/requirements.yaml
  jx-app-sso/values.schema.json
  jx-app-sso/values.yaml
Labels: approved, lgtm, size/L

#2 typo in approvers
  OWNERS
Labels: approved, lgtm, size/XS

#9 chore(deps): bump https://github.com/jenkins-x/dex from 2.13.16 to 2.…
  jx-app-sso/requirements.yaml
Labels: approved, lgtm, size/XS

#10 fix: create environment role bindings for google groups
  jx-app-sso/templates/committer-group-environmentrolebinding.yaml.yaml
  jx-app-sso/templates/owner-group-environmentrolebinding.yaml.yaml
  jx-app-sso/templates/viewer-group-environmentrolebinding.yaml.yaml
  jx-app-sso/values.schema.json
  jx-app-sso/values.yaml
Labels: approved, lgtm, size/L
